# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Admin/OneDrive/My_tnh/Design-Conv2D-using-HLS/Conv2D-design/Conv2D-design.srcs/sources_1/bd/Conv2D_design/ip/Conv2D_design_processing_system7_0_0/Conv2D_design_processing_system7_0_0.xci
# IP: The module: 'Conv2D_design_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Admin/OneDrive/My_tnh/Design-Conv2D-using-HLS/Conv2D-design/Conv2D-design.gen/sources_1/bd/Conv2D_design/ip/Conv2D_design_processing_system7_0_0/Conv2D_design_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Conv2D_design_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/Admin/OneDrive/My_tnh/Design-Conv2D-using-HLS/Conv2D-design/Conv2D-design.srcs/sources_1/bd/Conv2D_design/ip/Conv2D_design_processing_system7_0_0/Conv2D_design_processing_system7_0_0.xci
# IP: The module: 'Conv2D_design_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Admin/OneDrive/My_tnh/Design-Conv2D-using-HLS/Conv2D-design/Conv2D-design.gen/sources_1/bd/Conv2D_design/ip/Conv2D_design_processing_system7_0_0/Conv2D_design_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Conv2D_design_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
