# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/freedino/Design-Conv2D-using-HLS/Convolution2D/Convolution2D/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_convolution2D_0_0/design_1_convolution2D_0_0.xci
# IP: The module: 'design_1_convolution2D_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/freedino/Design-Conv2D-using-HLS/Convolution2D/Convolution2D/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_convolution2D_0_0/constraints/convolution2D_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_convolution2D_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/freedino/Design-Conv2D-using-HLS/Convolution2D/Convolution2D/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_convolution2D_0_0/design_1_convolution2D_0_0.xci
# IP: The module: 'design_1_convolution2D_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/freedino/Design-Conv2D-using-HLS/Convolution2D/Convolution2D/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_convolution2D_0_0/constraints/convolution2D_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_convolution2D_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
