#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("input_0_address0", 4, hls_out, 0, "ap_memory", "mem_address", 1),
	Port_Property("input_0_ce0", 1, hls_out, 0, "ap_memory", "mem_ce", 1),
	Port_Property("input_0_q0", 32, hls_in, 0, "ap_memory", "mem_dout", 1),
	Port_Property("input_0_address1", 4, hls_out, 0, "ap_memory", "MemPortADDR2", 1),
	Port_Property("input_0_ce1", 1, hls_out, 0, "ap_memory", "MemPortCE2", 1),
	Port_Property("input_0_q1", 32, hls_in, 0, "ap_memory", "MemPortDOUT2", 1),
	Port_Property("input_1_address0", 4, hls_out, 1, "ap_memory", "mem_address", 1),
	Port_Property("input_1_ce0", 1, hls_out, 1, "ap_memory", "mem_ce", 1),
	Port_Property("input_1_q0", 32, hls_in, 1, "ap_memory", "mem_dout", 1),
	Port_Property("input_1_address1", 4, hls_out, 1, "ap_memory", "MemPortADDR2", 1),
	Port_Property("input_1_ce1", 1, hls_out, 1, "ap_memory", "MemPortCE2", 1),
	Port_Property("input_1_q1", 32, hls_in, 1, "ap_memory", "MemPortDOUT2", 1),
	Port_Property("input_2_address0", 3, hls_out, 2, "ap_memory", "mem_address", 1),
	Port_Property("input_2_ce0", 1, hls_out, 2, "ap_memory", "mem_ce", 1),
	Port_Property("input_2_q0", 32, hls_in, 2, "ap_memory", "mem_dout", 1),
	Port_Property("input_2_address1", 3, hls_out, 2, "ap_memory", "MemPortADDR2", 1),
	Port_Property("input_2_ce1", 1, hls_out, 2, "ap_memory", "MemPortCE2", 1),
	Port_Property("input_2_q1", 32, hls_in, 2, "ap_memory", "MemPortDOUT2", 1),
	Port_Property("kernel_0_0", 32, hls_in, 3, "ap_none", "in_data", 1),
	Port_Property("kernel_0_1", 32, hls_in, 4, "ap_none", "in_data", 1),
	Port_Property("kernel_0_2", 32, hls_in, 5, "ap_none", "in_data", 1),
	Port_Property("kernel_1_0", 32, hls_in, 6, "ap_none", "in_data", 1),
	Port_Property("kernel_1_1", 32, hls_in, 7, "ap_none", "in_data", 1),
	Port_Property("kernel_1_2", 32, hls_in, 8, "ap_none", "in_data", 1),
	Port_Property("kernel_2_0", 32, hls_in, 9, "ap_none", "in_data", 1),
	Port_Property("kernel_2_1", 32, hls_in, 10, "ap_none", "in_data", 1),
	Port_Property("kernel_2_2", 32, hls_in, 11, "ap_none", "in_data", 1),
	Port_Property("output_r_address0", 4, hls_out, 12, "ap_memory", "mem_address", 1),
	Port_Property("output_r_ce0", 1, hls_out, 12, "ap_memory", "mem_ce", 1),
	Port_Property("output_r_we0", 1, hls_out, 12, "ap_memory", "mem_we", 1),
	Port_Property("output_r_d0", 32, hls_out, 12, "ap_memory", "mem_din", 1),
	Port_Property("output_r_address1", 4, hls_out, 12, "ap_memory", "MemPortADDR2", 1),
	Port_Property("output_r_ce1", 1, hls_out, 12, "ap_memory", "MemPortCE2", 1),
	Port_Property("output_r_we1", 1, hls_out, 12, "ap_memory", "MemPortWE2", 1),
	Port_Property("output_r_d1", 32, hls_out, 12, "ap_memory", "MemPortDIN2", 1),
};
const char* HLS_Design_Meta::dut_name = "convolution2D";
